from dash import dcc, html
import dash_bootstrap_components as dbc

custom_styles = {
    'container': {
        'width': '90%', 
        'margin': '2rem auto',
    },
    'header': {
        'text-align': 'center',
        'margin-bottom': '2rem',
        'color': '#4F46E5',
    },
    'subtitle': {
        'color': '#6B7280',
        'font-size': '1.1rem',
     
        'margin': '0 auto',
        'line-height': '1.6',
    },
    'card': {
        'background': '#ffffff',
        'border-radius': '1.5rem',
        'padding': '2.5rem',
        'box-shadow': '0 10px 25px rgba(0, 0, 0, 0.1)',
        'margin-bottom': '2rem',
        'border': '1px solid #E5E7EB',
    },
    'textarea': {
        'width': '100%',
        'min-height': '180px',
        'padding': '1.25rem',
        'border': '2px solid #E5E7EB',
        'border-radius': '0.75rem',
        'margin-bottom': '1rem',
        'font-size': '1.1rem',
        'resize': 'vertical',
        'transition': 'border-color 0.3s ease',
        'line-height': '1.5',
    },
    'button': {
        'background': 'linear-gradient(135deg, #4F46E5, #6366F1)',
        'color': 'white',
        'border': 'none',
        'padding': '1rem 2rem',
        'border-radius': '0.75rem',
        'font-size': '1.1rem',
        'font-weight': '600',
        'cursor': 'pointer',
        'width': '100%',
        'transition': 'all 0.3s ease',
        'margin-top': '1rem',
        'text-transform': 'uppercase',
        'letter-spacing': '0.05em',
    },
    'progress_container': {
        'margin-top': '2rem',
        'padding': '2rem',
        'border-radius': '1.5rem',
        'background': '#ffffff',
        'box-shadow': '0 4px 6px rgba(0, 0, 0, 0.1)',
        'border': '1px solid #E5E7EB',
    },
    'label': {
        'font-size': '1.1rem',
        'font-weight': '600',
        'letter-spacing': '0.025em',
    },
    'percentage': {
        'font-size': '1rem',
        'font-weight': '500',
        'color': '#374151',
    }
}

layout = html.Div([
    html.Div(
        style=custom_styles['container'],
        children=[
            # Header Section
            html.Div(
                style=custom_styles['header'],
                children=[
                    html.H1("AI Content Detector", 
                           style={'font-size': '2.5rem', 'font-weight': 'bold', 'margin-bottom': '1rem'}),
                    html.P(
                        "Analyze your text to determine if it's written by a human or generated by AI", 
                        style=custom_styles['subtitle']
                    )
                ]
            ),
            
            # Main Card Section
            html.Div(
                style=custom_styles['card'],
                children=[
                    dbc.Textarea(
                        id='text',
                        placeholder="Paste your text here for analysis...",
                        style=custom_styles['textarea']
                    ) 
                ]
            ),
            
            # Results Section
            html.Div(
                style=custom_styles['progress_container'],
                children=[
                    # Labels Row
                    dbc.Row([
                        dbc.Col(
                            html.H5('Human Written', 
                                   style={**custom_styles['label'], 'text-align': 'right', 'color': '#22C55E'}),
                            width=4
                        ),
                        dbc.Col(
                            dcc.Loading(
                                id='loading',
                                children=html.Div(''),
                                type="circle"
                            ),
                            width=4
                        ),
                        dbc.Col(
                            html.H5('AI Generated', 
                                   style={**custom_styles['label'], 'text-align': 'left', 'color': '#EF4444'}),
                            width=4
                        ),
                    ]),
                    
                    # Progress Bars
                    dbc.Row([
                        dbc.Col(
                            dbc.Progress([
                                dbc.Progress(
                                    id="real_prog",
                                    value=50,
                                    color="success",  # Changed to green
                                    bar=True,
                                    style={'transition': 'width 0.3s ease'}
                                ),
                                dbc.Progress(
                                    id="fake_prog",
                                    value=50,
                                    color="danger",  # Red color
                                    bar=True,
                                    style={'transition': 'width 0.3s ease'}
                                ),
                            ],
                            style={
                                'height': '30px',
                                'font-size': '16px',
                                'border-radius': '1rem',
                                'overflow': 'hidden',
                                'box-shadow': '0 2px 4px rgba(0, 0, 0, 0.05)',
                                'border': '1px solid #E5E7EB',
                            }),
                            width={"size": 8, "offset": 2}
                        ),
                    ]),
                    
                    # Percentage Display
                    dbc.Row([
                        dbc.Col(
                            html.Div(id='human-percentage', 
                                    style={**custom_styles['percentage'], 'text-align': 'right'}),
                            width=4
                        ),
                        dbc.Col(width=4),
                        dbc.Col(
                            html.Div(id='ai-percentage', 
                                    style={**custom_styles['percentage'], 'text-align': 'left'}),
                            width=4
                        ),
                    ], style={'margin-top': '1rem'})
                ]
            )
        ]
    )
])